list1:
  - java
  - c
  - python
  - html
  - css
  - mysql
  - reactjs
  - aws
  - nodejs
  - django
  - hadoop
  - hive
  - docker
  - kubernetes
  - postgresql
  - git
  - github
  - djangorestframework
